### ISSUE TITLE
feat: payload of call changed. 

### ISSUE THREAD

**Issue by sansan88** [project-owlly/signature#12]
To implement callable functions in firebase, I had to change the payload. 

https://europe-west6-project-owlly.cloudfunctions.net/OIDAuthUrl

`{"data":{"url":"https://eid.sh.ch/authorize?client_id=owllyApp&scope=openid%20given_name%20family_name%20birth_date%20street_address%20postal_code%20locality%20verified_simple&response_type=code&redirect_uri=https%3A%2F%2Fowlly.ch%2Freturn","token":"testtoken"}}`

**Comment by sansan88** [comment]
@peterpeterparker 
can you have a look at this? :) 
It's a small one..

**Comment by sansan88** [comment]
I'm more interested in what you think about the new payload?

**Comment by peterpeterparker** [comment]
@sansan88 what do you want? a feedback on the new payload structure or an enhancement of the component?

**Comment by sansan88** [comment]
Both! :) 
With firebase (callable) functions we have to add "data" to every response..

**Comment by peterpeterparker** [comment]
@sansan88 mmmmh well I am not sure why you say that you have to add "data"?

Link to code?

**Comment by sansan88** [comment]
https://github.com/project-owlly/site/blob/master/src/app/services/oidc.service.ts

https://github.com/project-owlly/site/blob/master/src/app/pages/return/return.page.ts

**Comment by peterpeterparker** [comment]
but it is not the client side which define the structure rather the cloud no? I don't get your issue.

**Comment by peterpeterparker** [comment]
```
this.oidc.getUserData(params.code).subscribe((userData) => {
          this.userData = userData.data.given_name; //  <------ userData.data is given / answer of the cloud
        });
```

**Comment by sansan88** [comment]
yes, as far as I know ( I can be wrong!) the data attribute in the answer of the cloud is mandatory to pass as an answer..
so you have to return a data attribute from the cloud to handle the request in your app

**Comment by peterpeterparker** [comment]
Ummm don't think so, at least it is not mentioned in the doc https://github.com/angular/angularfire/blob/master/docs/functions/functions.md

moreover the example does **not** contains it

```
@Component({
  selector: 'app-root',
  template: `{ data$  | async }`
})
export class AppComponent {
  constructor(private fns: AngularFireFunctions) { 
    const callable = fns.httpsCallable('my-fn-name');
    this.data$ = callable({ name: 'some-data' });
  }
}
```

so no, don't think you need that

**Comment by sansan88** [comment]
hmmm strange.. next time I have to write down the issue I had.. it's working now..

**Comment by peterpeterparker** [comment]
is it ? because  in the cloud function you are still returning `data`

https://github.com/project-owlly/cloud/blob/11d5da709eee32f470d544b8a7a63faf1965d650/functions/src/request/oidc/getOIDC.ts#L22

is: `response.json({data: oidAuth});`

should be `response.json(oidAuth);`

**Comment by sansan88** [comment]
yes :) 
https://github.com/project-owlly/cloud/pull/43

**Comment by sansan88** [comment]
you are too fast :)

**Comment by peterpeterparker** [comment]
cool 👍
